import Head from "next/head";
import ContainerFull from "../components/containerFull";
import Container from "../components/container";
import HeroSection from "../components/heroSection";
import Sponsors from "../components/sponsors";

export default function Home() {
  return (
    <>
      <Head>
        <title>The Duft Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerFull>
        <HeroSection />
        <Sponsors />
        <Container></Container>
      </ContainerFull>
    </>
  );
}
